
version: 2

sources:
  - name: DBTTESTEXAMPLES_DATABASE
    # The database line is where your BigQuery database name should go to contain the schema.
    # Enter it below:
    database: DBTTESTEXAMPLES_DATABASE
    # This schema should be under the database on line 7, where dbt will generate source tables there.
    # Enter it below:
    schema: DBTTESTEXAMPLES_SCHEMA

    quoting:
      database: false
      schema: false
      identifier: false

    tables:
      - name: games_src
        columns:
          - name: username
            tests:
              - not_null

          - name: deaths
            tests:
              - not_null

          - name: kills
            tests:
              - not_null

          - name: assists
            tests:
              - not_null

          - name: game_start
            tests:
              - not_null

          - name: game_end
            tests:
              - not_null

          - name: damage_done
            tests:
              - not_null

          - name: damage_taken
            tests:
              - not_null

          - name: win
            tests:
              - not_null

      - name: users_src
        columns:
          - name: username
            tests:
              - not_null

          - name: first_name
            tests:
              - not_null

          - name: last_name
            tests:
              - not_null

          - name: email
            tests:
              - not_null

          - name: date_joined
            tests:
              - not_null
